[project]
name = 'gigi_contracts'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.file_versioning]
path = 'contracts/file_versioning.clar'
clarity_version = 2
epoch = 2.5

[contracts.multi_send_and_access_control]
path = 'contracts/multi_send_and_access_control.clar'
clarity_version = 2
epoch = 2.5

[contracts.storage_with_deligated_updates]
path = 'contracts/storage_with_deligated_updates.clar'
clarity_version = 2
epoch = 2.5

[contracts.storage_with_freeze]
path = 'contracts/storage_with_freeze.clar'
clarity_version = 2
epoch = 2.5

[contracts.voting_with_multiple_role]
path = 'contracts/voting_with_multiple_role.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
